# Generated by Django 6.0.4 on 2026-04-30 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boutique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_produit', models.CharField(choices=[('smartphone', 'Smartphone'), ('accessoire', 'Accessoire'), ('tablette', 'Tablette'), ('autre', 'Autre')], default='smartphone', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('seuil_alerte', models.PositiveIntegerField(default=3, help_text='Alerte si le stock tombe en dessous de ce seuil')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stock.categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='stock.marque')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['marque__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('employe', 'Employé')], default='employe', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='stock.boutique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=0, help_text="Prix d'achat moyen en FCFA", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_vente_suggere', models.DecimalField(decimal_places=0, help_text='Prix conseillé au vendeur', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_dernier_arrivage', models.DateField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.boutique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Stock Boutique',
                'unique_together': {('produit', 'boutique')},
            },
        ),
        migrations.CreateModel(
            name='SmartphoneIMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=17, unique=True)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('stockage', models.CharField(blank=True, help_text='Ex: 128GB, 256GB', max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu'), ('defectueux', 'Défectueux'), ('retour', 'Retour SAV')], default='disponible', max_length=20)),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('date_vente', models.DateField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='stock.stockboutique')),
            ],
            options={
                'verbose_name': 'Smartphone (IMEI)',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('credit', 'Crédit')], default='especes', max_length=20)),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='stock.boutique')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imei', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_vente', to='stock.smartphoneimei')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='stock.stockboutique')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.vente')),
            ],
            options={
                'verbose_name': 'Ligne de Vente',
            },
        ),
    ]
