# Generated by Django 6.0.4 on 2026-05-01 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeArrivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('arrivage', 'Arrivage stock existant'), ('nouveau_produit', 'Nouveau produit')], default='arrivage', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('nom_produit', models.CharField(blank=True, max_length=200)),
                ('type_produit', models.CharField(blank=True, max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_arrivage', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('imeis_json', models.TextField(blank=True, default='[]')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('prix_vente_suggere', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('notes_patron', models.TextField(blank=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='stock.boutique')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categorie')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.marque')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='stock.stockboutique')),
            ],
            options={
                'verbose_name': "Demande d'arrivage",
                'ordering': ['-date_creation'],
            },
        ),
    ]
