# Generated by Django 6.0.4 on 2026-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_vente_reelle',
            field=models.DateField(blank=True, help_text="Date réelle de la vente si différente d'aujourd'hui", null=True),
        ),
    ]
