# Generated by Django 6.0.4 on 2026-06-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_vente_date_vente_reelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('motif', models.CharField(choices=[('arrivage', 'Arrivage'), ('vente', 'Vente'), ('retour', 'Retour'), ('correction', 'Correction manuelle'), ('perte', 'Perte / Casse')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.stockboutique')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
